updated to vue.js
Egorchik231/JS_Second pull request #4
Opened 2020-09-06 12:34 UTC by Egorchik231

2020-09-06 19:07 UTC, Om1X requested changes

2020-09-06 19:07 UTC, Om1X commented on index.html
> +            <button class="btn-cart" type="button" @click="() => {cart_block === 'cart-block' ? this.cart_block = 'cart-block invisible' : this.cart_block = 'cart-block'}">Корзина</button>
Зачем так усложнять? Достаточно одно поля isVisible и по клику менять его значение. А далее на блоке корзины обычный v-show="isVisible"

2020-09-11 18:21 UTC, closed without merging

2020-09-11 18:28 UTC, Egorchik231 commented
https://github.com/Egorchik231/JS_Second/pull/5
Ссылка была заглушкой! Выше новый пулреквест

2020-09-11 18:28 UTC, Egorchik231 commented on index.html
> +            <button class="btn-cart" type="button" @click="() => {cart_block === 'cart-block' ? this.cart_block = 'cart-block invisible' : this.cart_block = 'cart-block'}">Корзина</button>
#5
Ссылка была заглушкой! Выше новый пулреквест